# frozen_string_literal: true

module MediaWiktory
  # Default wrapper for lates MediaWiki API available of English Wikipedia; generated by MediaWiki.
  #
  # Most of the time .....
  module Wikipedia
  end
end
